### ISSUE TITLE
Does not compile with node 0.6.5

### ISSUE THREAD

**Issue by cweiske** [0xfeedface/node_raptor#5]
While I can compile `node_raptor` with node-0.3.0, it does not do so for node version 0.6.5. You will get the following error:

```
$ LC_ALL=C node-waf configure build
Setting srcdir to                        : /root/node_raptor 
Setting blddir to                        : /root/node_raptor/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /root/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.039s)
Waf: Entering directory `/root/node_raptor/build'
[1/5] cxx: src/bindings.cc -> build/Release/src/bindings_1.o
[2/5] cxx: src/parser.cc -> build/Release/src/parser_1.o
In file included from ../src/bindings.cc:19:
../src/parser.h:21:25: error: node_events.h: No such file or directory
In file included from ../src/parser.cc:24:
../src/parser.h:21:25: error: node_events.h: No such file or directory
In file included from ../src/bindings.cc:19:
../src/parser.h:35: error: expected class-name before '{' token
In file included from ../src/bindings.cc:20:
../src/serializer.h:32: error: expected class-name before '{' token
In file included from ../src/parser.cc:24:
../src/parser.h:35: error: expected class-name before '{' token
../src/statics.h:49: warning: 'world' defined but not used
../src/parser.cc: In static member function 'static v8::Handle<v8::Value> Parser::Initialize(const v8::Arguments&)':
../src/parser.cc:31: error: 'EventEmitter' has not been declared
../src/parser.cc: In static member function 'static v8::Handle<v8::Value> Parser::New(const v8::Arguments&)':
../src/parser.cc:78: error: 'class Parser' has no member named 'Wrap'
../src/parser.cc: In member function 'void Parser::ParseFile(const char*, const char*)':
../src/parser.cc:294: error: 'Emit' was not declared in this scope
../src/parser.cc: In member function 'void Parser::ParseURI(const char*, const char*)':
../src/parser.cc:317: error: 'Emit' was not declared in this scope
../src/parser.cc: In member function 'void Parser::ParseBuffer(const char*, size_t, bool)':
../src/parser.cc:345: error: 'Emit' was not declared in this scope
../src/parser.cc: In member function 'void Parser::StatementHandler(raptor_statement*)':
../src/parser.cc:387: error: 'Emit' was not declared in this scope
../src/parser.cc: In member function 'void Parser::NamespaceHandler(raptor_namespace*)':
../src/parser.cc:407: error: 'Emit' was not declared in this scope
../src/parser.cc: In member function 'void Parser::LogMessageHandler(raptor_log_message*)':
../src/parser.cc:414: warning: enumeration value 'RAPTOR_LOG_LEVEL_NONE' not handled in switch
../src/parser.cc:414: warning: enumeration value 'RAPTOR_LOG_LEVEL_TRACE' not handled in switch
../src/parser.cc:437: error: 'Emit' was not declared in this scope
Waf: Leaving directory `/root/node_raptor/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx bindings.cc -> bindings_1.o}
 -> task failed (err #1): 
    {task: cxx parser.cc -> parser_1.o}
```
